name: Deploy to Firebase Hosting for App on PR
'on': pull_request

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Creating & Initializing env variables for Frontend Package
        run: |
          cd packages/frontend
          pwd
          echo "GATSBY_APP_API_KEY= ${{secrets.GATSBY_APP_API_KEY}}
          GATSBY_APP_AUTH_DOMAIN= ${{secrets.GATSBY_APP_AUTH_DOMAIN}}
          GATSBY_APP_PROJECT_ID= ${{secrets.GATSBY_APP_PROJECT_ID}}
          GATSBY_APP_STORAGE_BUCKET= ${{secrets.GATSBY_APP_STORAGE_BUCKET}}
          GATSBY_APP_MESSAGING_SENDER_ID= ${{secrets.GATSBY_APP_MESSAGING_SENDER_ID}}
          GATSBY_APP_APP_ID= ${{secrets.GATSBY_APP_APP_ID}}
          GATSBY_APP_MEASUREMENT_ID= ${{secrets.GATSBY_APP_MEASUREMENT_ID}}" > .env
      - name: Build the project
        run: |
          yarn
          yarn build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FAHAD_WEB }}'
          projectId: fahad-web
